<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icon.ico" />
    <None Remove="Resources\icon_active.ico" />
    <None Remove="Resources\icon_inactive.ico" />
    <None Remove="Resources\icon_menu.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icon.ico" />
    <Resource Include="Resources\icon_active.ico" />
    <Resource Include="Resources\icon_inactive.ico" />
    <Resource Include="Resources\icon_menu.ico" />
  </ItemGroup>

</Project>
